---
title: "ESMA 6605: Introduccion y Estadistica Descriptiva"
format:
  html:
    code-fold: true
jupyter: python3
---

# Muestreo

- Queremos hacer inferencias sobre la población usando una muestra que extraemos de ella. No cualquier muestra
puede usarse como base para hacer inferencias validas. Muestras por conveniencia o muestras donde se piden 
voluntarios podrían llevar a conclusiones sesgadas (polarizadas). Algunas observaciones pueden ocurrir mas 
frecuentemente de lo que ocurren en la población y otras menos frecuentemente de lo que ocurren en la población.

- Ejemplos: encuestas en el radio, recistas, TV; estudio xlinixo xon precientes mas enfermos

El componente aleatorio deb eestar presente en la forma en que seleccionamos la muestra. Esto amuenta la probabilidad 
de obtener una muestra que tnega la dicersidad de caracteristicas que tienen la problacion y ademas permite usar la 
probabilidad para hacer inferencias. A continuaxion algunos metodos de muestreo. En cualquier caso se debe tener una
lista de todos los elemntos de la poblacion (*sampling frame).

1. Muestras aleatorias simple:
    - **Definicion**: una muestra de tamano $n$ es seleccionada al azar de modo que todas las muestras de tamano $n$ 
      tiene la misma probabilidad de ser seleccionadas.
    - **En la praactica**: Se obtien seleccionando un individuo a la vez, al azar y sin reemplazo de la poblaccion 
      hasta obtener un muestra de tamano $n$. Para hacer la seleccion a azar pueede usar una tabla de numero aleatorios, 
      culculadora o aplicacion de computadoras como MINITAB, R, etc.
    - **Nota**: De seleccionarse los individuos a la muestra al azar y con reemplazo tenedremos lo que se conoce como 
      muestra alewatoriDe seleccionarse los individuos a la muestra al azar y con reemplazo tenedremos lo que se conoce como muestra alewatoria.

Problema: Desea hacer un estudio para evualar el proceso de matricula de los estudiantes subgraduados en el RUM. Decide tomar una muestra de 1000 
estudiantes subgraduados de una lista que tiene que los divide por facultad.

| Facultad | Estudiantes |
|----------|-------------|
| Ciencias Agricolas | 955 |
| Ciencias | 3,083 |
| Artes | 1,969 |
| Administracion de Empresas | 1,388 |
| Ingenieria | 4,694 |
| Educacion | 103 |
| Total | 12,191 |

2. **Muestra Estratificada**: La población esta dividida en estratos o grupos típicamente homogéneos.
De cada estrato se toma una muestra aleatoria simple. La union de todas estas muestras es la muestra estratificada.
La muestra aleatoria simple puede ser propocinal al tamano del estrato.

3. **Muestra por Conglomerados**: La poblacion esta dividida en grupos. Se obtien una muestra aleatoria simple de grupos. La muestra por 
conglomerados es la union de todos los inidviduos en losgrupos seleccionadfos.

4. **Muestra Sistematica**: Se selecciona a la muetra un primer individuo al azar. A partir de este se sxeleccionan individuos a la misma 
distancia en la lista de la poblacion hasta obtener el tamano de muestras deseado. Por ejemplo si la poblacion tiene 100 individuos y quiere una muestra de 
5 individuos. Selecciona el primer individuo al azar entre los primeros 20 individuos ($\frac{100}{5} = 20$). Suponga que selecciona al individuo en la posicion numero 4 
luego  se selecciona los individuos en las posiciones 4, 24, 44, 64 y 84.

# Recolecion de Datos 

- **Ejemplo 1**: Se investigó el riesgo de desarrollar cáncer en usuarios de teléfonos celulares en
Dinamarca. Investigadores siguieron a 420,095 personas que tuvieron su primer celular entre
1982 y 1995. En el 2002, determinaron la frecuencia de tumor cerebral en estos individuos y la
compararon con la frecuencia de tumor cerebral en la población general. Los científicos no
encontraron diferencia significativa entre los dos grupos por lo que concluyeron que el uso del
teléfono celular no está asociado al incremento en el riesgo de desarrollar tumor cerebral. (Schüz
et al., 2006, Cellular Phone Use and Cancer Risk: Update of a Nationwide Danish Cohort,
Journal of the National Cancer Institute 98(23))

- **Ejemplo 2**: Se investigó el riesgo de desarrollar tumor cerebral por la exposición a dos
radiofrecuencias comunes en los teléfonos celulares: 835.62 MHz y 847.74 MHz. Investigadores
dividieron aleatoriamente 480 ratas en 3 grupos. Un grupo fue expuesto a la radiofrecuencia
835.62 MHz, otro grupo a la radiofrecuencia 847.74 MHz y el otro no recibió radiación. Las
ratas recibieron radiación 4 horas al día, cinco días a la semana por dos años. Las ratas en los tres
grupos recibieron el mismo cuidado excepto por la exposición a la radiación. Después de 505
días de exposición los científicos no encontraron aumento significativo en ningún tipo de tumor
en las ratas expuestas a radiación comparadas con las que no estuvieron expuestas a la radiación.
(La Regina et al., The effect of chronic exposure to 835.62 MHz FMCW or 847.74 MHz CDMA
on the Incidence of Spontaneous Tumors in Rats, Bioelectromagnetic Society Conference 2002)

1. **Censo**: listado de las variables de interes de todos los elementos de la poblacion

2. **Estudios observacionales**: Se estudia las caracterisitcas de interes sin tratar de manipularla, 
influenciarla o controlarla.
  - Tipos De estudios observacionales:
     - Case Report\Case Series – Estudios descriptivos que siguen un pequeño número
       de sujetos. Ejemplo: Ver Pneumocystis Pneumonia, Páginas 729-733.
     - Estudios Transversales (Cross-sectional Studies) – El conjunto de datos se obtiene
       sólo en un tiempo particular. Ejemplo: Encuestas de opinión del Periódico Nuevo
       Día
     - Estudios Prospectivos (Prospective Studies or Longitudinal studies) – El conjunto
       de datos se obtiene en el futuro luego de monitorear a grupos de participantes
       (cohorts) en el tiempo. Ejemplo: Ver
       https://www.framinghamheartstudy.org/about-fhs/index.php
     - Estudios Retrospectivos (Retrospective Studies) – El conjunto de datos se obtiene
       examinando el tiempo pasado (records, entrevistas) de un grupo de participantes.
       Ejemplo: Estudio para aprender sobre el efecto del consumo del ácido fólico
       durante el embarazo en nacimientos con espina bífida. Se toma una muestra de
       mujeres que han tenido hijos. Para esta muestra se colecta información sobre el
       estado al nacer del bebé (espina bífida/no bífida), uso del ácido fólico durante el
       embarazo, posiblemente también información sobre dieta, ejercicio, condición de
       salud, etc.
     - Case-Control Studies – los participantes se escogen de acuerdo a la variable de
       interés y el conjunto de datos se obtiene examinando el tiempo pasado (records,
       entrevistas) de estos participantes. Ejemplo: Estudio para aprender sobre el efecto
       del consumo del ácido fólico durante el embarazo en nacimientos con espina
       bífida. Se toma una muestra de mujeres que han tenido hijos con espina bífida y
       otra muestra de mujeres que han tenido hijos sin espina bífida. Para cada muestra
       se colecta información sobre el uso del ácido fólico durante el embarazo,
       posiblemente también información sobre dieta, ejercicio, condición de salud, etc
  - Solo se puede establecer asociacion y no cause ya que pueden ecisxtir otras variables 
    que no se tomaron en cuenta (*lurking variables*) que potencialmente afectan la variable 
    de interes y no has sido consideradas en el estudio.

3. **Expermentos**: se estudia la caracteristicas de interes (variables repuestas) mientras se 
controlan otras cariables (trataminetos) que pueden influenciarla con el proposito de medir como los cambios 
en las variables repuesta.
  - Que variables pueden afectar la cariables de interes? Cuales de estas?
    - Minimizar el efecto de las cariables que  no se pueden controlar 
    - Aumentar la probabilidad de obtener una muestra con la dicersidad de caracteristicas de la poblacion 
  - Replicacion (*replication*): los tratamientos son asignados a mas de una unidad experimental
    - Resultado no sea producto de una caracterisitca particular de alguno de ellos
    - Aumentar la probabilidad causa y efecto
  - Se puede establecer casusa y efecto

# Diseño de Experimentos

Puede leer más detalles en su libro de texto o en cualquier libro de Diseño de Experimentos
(Experimental Design). Los diseños de experimentos buscan evitar, entre otras cosas, los efectos
confundidos (confounding effects) que ocurren cuando no se puede identificar el efecto de los
tratamientos en la variable respuesta

**Diseno Completamente Aleatorizado**: (Completely Randomized Design) - Cada unidad eperimental es asignada a un tratamiendo aleatoriamente.
  - Ejemplo: En un hospital psiquiátrico se quiere comparar cinco métodos distintos para remotivar
    pacientes. Se seleccionaron 20 pacientes del hospital aleatoriamente y a cada uno se le asignó
    aleatoriamente uno de los cinco métodos de remotivación de manera que hubiera cuatro
    pacientes por método. Al final del periodo experimental los pacientes fueron evaluados por un
    grupo de expertos que no conocían el método asignado a los pacientes. Los expertos asignaron
    un índice de motivación a cada paciente. ¿Se podrá concluir que hay diferencias en las medias
    del nivel de motivación para los distintos métodos de remotivación?

|A|B|C|D|E|
|---|---|---|---|---|
|58|68|60|68|64|
|62|70|65|80|69|
|67|70|65|80|69|
|70|81|70|89|74|
