---
title: "ESMA 6605: Inferencia"
format:
  html:
    code-fold: True
jupyter: python3
---


# Intervalos de Confianza para $\mu$

## Problema 1

Un grupo de nutritionist's desea estimar el contenido de proteínas de cierta comidad
enlatada. Obtuvo una muestra aleatoria de 18 latas y para cada lata se midio el ontenido de proteinas. 
El conjunto de datos se  muestra a continuacion.
$$ S = \{ 5.1, 4.9, 6.0, 5.0, 6.7, 5.5, 4.9, 6.1, 6.0, 5.8, 5.2, 4.7, 4.2, 4.9, 5.5, 5.6, 5.8, 6.0 \} $$

Asuma que la poblacion, o sea, el contenido de proteinas de todads las latas en esta comida enlatada tiene distribucio
normal con desviacion estadas tiene distrivucion normal xon desciacion estandasr 0.7 gramos. (Caso no real, la desciaxion
estandar de la poblacion es usualmente desxonoxida, asi como la media.)

1. Construya un intervalo de confianza del 95% para le media del contenido de proteinas en esta  comida enlatada.
Indique la interpretaxion de este intervalo.

```{python}
import numpy as np
import statsmodels.api as sm
import scipy.stats as stats
import matplotlib.pyplot as plt
S = np.array([5.1, 4.9, 6.0, 5.0, 6.7, 5.5, 4.9, 6.1, 6.0, 5.8, 5.2, 4.7, 4.2, 4.9, 5.5, 5.6, 5.8, 6.0])
mean = S.mean()
std = S.std()
ic_right = round(mean + 1.96 * 0.7 / np.sqrt(18), 2)
ic_right2 = round(mean + 1.96 * std / np.sqrt(18), 2)
ic_left = round(mean - 1.96 * 0.7 / np.sqrt(18), 2)
ic_left2 = round(mean - 1.96 * std / np.sqrt(18), 2)
print(ic_left, ic_right)
print(ic_left2, ic_right2)
```
  - **Interpretacion**: Hay un 95% de confianza de que el promedio de proteninas esta comida enlatada esta entre 5.12 y 5.76 gramos.
  - **Parametro de Interes**: promedio del xontenido de proteinas esta comida enlatada

2. Construya un intercalo deconfianza del 99% para la media del contenido de proteinas en esta comida enlatada. 
Indique la interpretaxion de este intercalo.
```{python}
ic_right = round(mean + 2.58 * 0.7 / np.sqrt(18), 2)
ic_left = round(mean - 2.58 * 0.7 / np.sqrt(18), 2)
print(ic_left, ic_right)
```

3. Construlla un intervalo de confianzadel 90% para la media del contenido de proteinas en esta comida enlatada.
Indique la interpretacion de este intercalo.
```{python}
ic_right = round(mean + 1.645 * 0.7 / np.sqrt(18), 2)
ic_left = round(mean - 1.645 * 0.7 / np.sqrt(18), 2)
print(ic_left, ic_right)
```

Observe esto intervalo, Que puede deir sobre el anxho de ellos y el nivel de xonfianza correspondiente?

- A la medida que el nivel de confianza aumenta, el ancho del intervalo de confianza tambien aumenta.

Sea $X_1, X_2, \ldots, X_n$ de una distribucion normal con medidia $\mu$ y  varianza $\sigma^2$. Entonces,
$$ \frac{1}{n} \sum_{i=1}^n X_i = \bar{X} \sim N(\mu, \frac{\sigma^2}{n}) $$

Por lo tanto,
$$ \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \sim N(0, 1) $$

Podemos encontrar $a$ y $b$ tal que 
$$ P(a \leq \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \leq b) = 1 - \alpha $$
$$ \implies P(\bar{X} - a \frac{\sigma}{\sqrt{n}} \leq \mu \leq \bar{X} + b \frac{\sigma}{\sqrt{n}}) = 1 - \alpha $$
$$ \implies P(\bar{X} - z_{\alpha/2} \frac{\sigma}{\sqrt{n}}, \bar{X} + z_{\alpha/2} \frac{\sigma}{\sqrt{n}})$$

## Ejemplo 2

Un grupo de nutricionistas desea estimar el contenido de proteínas de cierta
comida enlatada. Obtuvo una muestra aleatoria de 18 latas y para cada lata se midió el
contenido de proteínas. El conjunto de datos se muestra a continuación.
$$ S = \{ 5.1, 4.9, 6.0, 5.0, 6.7, 5.5, 4.9, 6.1, 6.0, 5.8, 5.2, 4.7, 4.2, 4.9, 5.5, 5.6, 5.8, 6.0 \} $$

1. Construya un intervalo de confianza del 95% para la media del contenido de proteínas
en esta comida enlatada. Indique la interpretación de este intervalo.

### Alternaticas:

$Var(S^2_n) \rightarrow 0$ cuando $n \rightarrow \infty$, entonces, $S^2_n$ es la probbilidad. Por el Teorema de Slutsky 
$$ \frac{\bar{X} - \mu}{S_n / \sqrt{n}} \sim t_{n-1} $$
$$ \implies \bar{X} \pm t_{n-1, \alpha/2} \frac{S_n}{\sqrt{n}} $$

Sea $X_1, X_2, \ldots, X_n$ de una distribucion normal con medidia $\mu$ y  varianza $\sigma^2$. Entonces,
$$ \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \sim t_{n-1} $$
$$ \implies \bar{X} \pm t_{n-1, \alpha/2} \frac{\sigma}{\sqrt{n}} $$

# Interpretaccion Probabilistica de los IC

Ejemplo: Ic del 95% en el problema de las latas 
$$ \bar{X} \pm z \frac{\sigma}{\sqrt{n}} \implies \bar{X} \pm 1.96 \frac{0.7}{\sqrt{18}} \implies \bar{X} \pm .31$$

Que sabemos de la distribucion de los promedios (n=18)?
```{python}
import matplotlib.pyplot as plt
from scipy.stats import norm

#x-axis ranges from -3 and 3 with .001 steps
x = np.arange(-3, 3, 0.001)

#plot normal distribution with mean 0 and standard deviation 1
plt.plot(x, norm.pdf(x, 0, 1))
```
- **Interpretacion**: Si repite el estudio $N$ veces, o sea, recolecta  18 latas $N$ veces y calcula las $N$ qq

```{python}
stats.ttest_ind(S, S)
```

## Ejemplo 3

El ingeniero de control de calidad de una compañía de dulces de chocolate desea investigar si la
recalibración de la máquina de llenado de los moldes de las barras de chocolate resultó en la
generación de barras con pesos más consistentes. Antes de recalibrar la máquina la desviación
estándar del peso de las barras era 0.75 gramos. El ingeniero tomó una muestra aleatoria de
barras de chocolate y obtuvo los siguientes pesos (en gramos).
$$S = \{ 19.68, 20.66, 19.98, 20.65, 19.61, 20.55, 20.36, 21.02, 21.50, 19.74, 19.56 \}$$

```{python}
S = np.array([19.68, 20.66, 19.98, 20.65, 19.61, 20.55, 20.36, 21.02, 21.50, 19.74, 19.56])
S.std()
x = 6163/np.sqrt(40)
13400 - 974 * 3
```
