---
title: "ESMA 6605: Homework 3"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
jupyter: python3
---


```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
```
## Problema 1

Se estudia el tiempo de reacción en humanos midiendo el tiempo que toma agarrar un objeto que va cayendo. 
Se desea determinar si en promedio el tiempo de reacción cuando se usa la mano dominante es menor a cuando 
de usa la mano no dominante. Se hizo un estudio con 12 individuos. Para cada uno de ellos se midió el tiempo 
de reacción separadamente en cada mano y la mano en que primero se midió la reacción fue escogida aleatoriamente. 
A continuación, el tiempo en segundos que les tomó agarrar el objeto que iba cayendo, tanto con la mano dominante 
como con la mano no dominante.


| Individuo | Mano dominante | Mano no dominante |
| --------- | -------------- | ----------------- |
| 1         | 0.177          | 0.179             |
| 2         | 0.219          | 0.202             |
| 3         | 0.186          | 0.208             |
| 3         | 0.189          | 0.184             |
| 4         | 0.198          | 0.215             |
| 5         | 0.194          | 0.193             |
| 7         | 0.160          | 0.194             |
| 8         | 0.163          | 0.160             |
| 9         | 0.166          | 0.209             |
| 10        | 0.152          | 0.164             |
| 11        | 0.190          | 0.210             |
| 12        | 0.172          | 0.197             |

*El parámetro de interés*: Es la diferencia en el promedio entre la mano dominante (MD) y mano no dominante (MND). 
Esto es un problema de promedios con muestras dependientes
#### Hipótesis
esto en una prueba de hipótesis de 
* $H_o: \mu_d \geq 0$
* $H_a: \mu_d < 0$ 

```{python}
data = np.array([[0.177, 0.179],
                  [0.219, 0.202],
                  [0.186, 0.208],
                  [0.189, 0.184],
                  [0.198, 0.215],
                  [0.194, 0.193],
                  [0.160, 0.194],
                  [0.163, 0.160],
                  [0.166, 0.209],
                  [0.152, 0.164],
                  [0.190, 0.210],
                  [0.172, 0.197]])
df = pd.DataFrame(data, columns=['dominante', 'no_dominante'])
df['diff'] = df['dominante'] - df['no_dominante']
```

```{python}
sd = df['diff'].std()
mean = df['diff'].mean()
n = len(df)
t = mean/(sd/np.sqrt(n))
upper = round(mean + 2.201*sd/np.sqrt(n), 3)
lower = round(mean - 2.201*sd/np.sqrt(n), 3)
interval = [lower, upper]
print(f'mean: {round(mean, 3)}')
print(f'sd: {round(sd, 3)}')
print(f't: {round(t, 3)}')
print(f'interval: {interval}')
```

```{python}
stats.ttest_rel(df['dominante'], df['no_dominante'], alternative='less')
```

## Interpretación
el valor criticó para esta prueba es 0.0165 y al ser menor que 0.05 rechazamos nuestra 
hipótesis nula y aceptamos nuestra hipótesis alterna. En el contexto del problema tenemos suficiente evidencia para concluir que 
el tiempo de reacción de la mano dominante es menor que la mano no dominante.
